services:
  - type: web
    name: detect-ai
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -e ".[web]"
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
